### ISSUE TITLE
Documentation Not loading

### ISSUE THREAD

**Issue by harshilparmar** [spotify/backstage#2448]
As mentioned in #2416.
Facing issue while setting initial development environment.

## Current Behavior
Documentation component not loading as expected!!
![error](https://user-images.githubusercontent.com/45915468/93024857-11b55a80-f617-11ea-9c60-cf1124a093b1.PNG)
Backend log.
![log](https://user-images.githubusercontent.com/45915468/93024862-167a0e80-f617-11ea-831c-34dd97929341.PNG)

## Steps to Reproduce
1. sync local branch with remote repo 
2. git fetch upstream
3. git merge upstream/master
4. yarn start in root folder
5. cd .\packages\backend\
6. yarn start

## Context
I just trying to solve #2416,But I can't due to this error.

## Environment

- NodeJS Version (v12.16.1):
- Operating System and Version : Windows 10 pro (64 bit)
- Browser Information:
1. Google chrome (Version 85.0.4183.102)
2. Mozilla firefox (80.0.1)

**Comment by braino15** [comment]
Facing exact same issue, with latest code (rebased 30 mins before). Key addition to above is, extra error for window's path being too long for   failed to stat 'C:/Users/XXXXXXX/AppData/Local/Temp/backstage-repo/github.com/spotify/backstage/master/plugins/scaffolder-backend/sample-templates/spr
ingboot-grpc-template/{{cookiecutter.component_id}}/src/main/java/com/example/{{cookiecutter.java_package_name}}/Application.java': The filename or extension is too long.

**Comment by emmaindal** [comment]
Hey @harshilparmar and @braino15 this might have been fixed in #2457 
Can you update us on if you still see this issue? Thanks!

**Comment by harshilparmar** [comment]
> 
> 
> Hey @harshilparmar and @braino15 this might have been fixed in #2457
> Can you update us on if you still see this issue? Thanks!


Now I am getting different error
![error](https://user-images.githubusercontent.com/45915468/93473923-3c9ff700-f914-11ea-8853-b5df60ea3733.PNG)

**Comment by OrkoHunter** [comment]
@harshilparmar Glad that "Documentation not loading" is fixed for you! :) (I will close this issue now)

Regarding your issue with `scaffolder.github.token`, the scaffolder in Backstage (a service which requires helps you to choose a Software Template and create a new project) needs a `GITHUB_ACCESS_TOKEN` to work. [Reference doc](https://backstage.io/docs/features/software-templates/installation#running-the-backend)

And you can obtain `GITHUB_ACCESS_TOKEN` in the following ways ->
- Go to https://github.com/settings/tokens
- Click “Generate new token”
- Check the “repo” permission. Name it anything relevant.
- Click “Generate token”.

And then you can either use `GITHUB_ACCESS_TOKEN="X" yarn start` in the backend or "export" this environment variable when you do yarn start.

**Comment by harshilparmar** [comment]
@OrkoHunter  Sorry but I still getting errors

![docError](https://user-images.githubusercontent.com/45915468/93609181-26179f80-f9e9-11ea-89fe-bcc06a433a88.PNG)
![error](https://user-images.githubusercontent.com/45915468/93609190-27e16300-f9e9-11ea-81ba-cb08c3da0343.PNG)

**Comment by OrkoHunter** [comment]
@harshilparmar No worries! 😄 Please keep create a new bug ticket here - it looks different than this issue.

**Comment by FabianHippmann** [comment]
@harshilparmar - also had this issue & was able to solve it in this issue -> https://github.com/spotify/backstage/issues/2518#issuecomment-694913148

**Comment by harshilparmar** [comment]
@FabianHippmann Thanks for suggestion brother,I have added username in `plugins\techdocs-backend\src\helpers.ts` ,but that's not works for me 😕
