### ISSUE TITLE
Add GitLab Auth

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#343]
Waiting for #366

**Comment by ldemailly** [comment]
does it mean this is solved through http://www.passportjs.org/packages/passport-gitlab/ ?

**Comment by stefanalund** [comment]
@ldemailly GitLab is not solved yet, but we have indeed built our auth around Passport. Hopefully it should be easy enough to add new auth providers by following the existing Google and GitHub auth examples that we have implemented.

Some documentation can be found here: https://github.com/spotify/backstage/tree/master/docs/auth

Let us know if you would be interested in giving GitLab auth a go 😄 🚀

**Comment by timurista** [comment]
Thanks @freben . This is looking good. But gitlab auth seems to have a broken part for the URI
I don't think this is complete yet, I merged from master and the redirect URI seems return part seems broken:

I pulled from master in commit: b92e1533d1930511e0dba2a753db3821d873aafc
after Merge pull request #1494 from daviddyball/master

I got the GItlab id, client secret and host.
I used the localhost backend locally to test the URI

this was generated from the popup
```
https://gitlab.eng.roku.com/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A7000%2Fauth%2Fgitlab%2Fhandler%2Fframe%3Fenv%3Ddevelopment&scope=read_user&state=XXX%3D%3D&client_id=XXX
```
decoded reference:
```https://gitlab.eng.roku.com/oauth/authorize?response_type=code&redirect_uri=http://localhost:7000/auth/gitlab/handler/frame?env=development&scope=read_user&state=XXX==&client_id=XXX
```
But this seems wrong. Our gitlab page loads, but the uri response return this:
`The redirect URI included is not valid.` from the iframe popup for gitlab.

**Comment by freben** [comment]
@danztran  any idea about the above?

**Comment by Rugvip** [comment]
@timurista What redirect URI did you configure? Usually you need to include the `?env=development` bit too

**Comment by timurista** [comment]
`http://localhost:7000?env=development` <--- configured for gitlab.
Still getting redirect issue

**Comment by Rugvip** [comment]
@timurista it should be `http://localhost:7000/auth/gitlab/handler/frame?env=development `

**Comment by timurista** [comment]
Ok yes thanks @Rugvip that works.
However it doesn't appear to change guest status.

![image](https://user-images.githubusercontent.com/4718607/86182477-e5dd0b00-bae4-11ea-8bb6-06f9964fbcab.png)


Seems like the username information hardcoded to github => 
```
  const api = useApi(gitOpsApiRef);
  const githubAuth = useApi(githubAuthApiRef);
  const [githubAccessToken, setGithubAccessToken] = useState(String);
  const [githubUsername, setGithubUsername] = useState(String);
```
I was expecting the word guest to update with details from auth provider. 
maybe profile info isn't mapping for gitlab. Checking now. https://github.com/spotify/backstage/blob/c1806a0e2d479615def038ffccb546a140a71f3f/plugins/auth-backend/src/providers/gitlab/provider.ts#L69-L71

**Comment by timurista** [comment]
OK no that looks good on backend.
getting correct adapted info:
```
PROFILE ADAPTED {
  email: '...',
  picture: 'https://gitlab...avatar/955/avatar.png',
  displayName: 'Tim Urista'
}
```

**Comment by timurista** [comment]
Problem is the email is only id you get from gitlab.
Here's PR working on https://github.com/spotify/backstage/pull/1500

**Comment by Rugvip** [comment]
Fixed by #1478 and #1500

**Comment by timurista** [comment]
The problem was the backstageIdentity wasn't propagating from the backend. We fixed it by parsing the id from the email. Check the MR for the fix

**Comment by raosumanth** [comment]
Finally what is the Callback URL. I am finding hard to get this as everything I try leads to The redirect URI included is not valid.
